// Generated by gencpp from file pkg_ros_iot_bridge/msgRosIotResult.msg
// DO NOT EDIT!


#ifndef PKG_ROS_IOT_BRIDGE_MESSAGE_MSGROSIOTRESULT_H
#define PKG_ROS_IOT_BRIDGE_MESSAGE_MSGROSIOTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_ros_iot_bridge
{
template <class ContainerAllocator>
struct msgRosIotResult_
{
  typedef msgRosIotResult_<ContainerAllocator> Type;

  msgRosIotResult_()
    : final_x(0)
    , final_y(0)
    , final_theta(0)  {
    }
  msgRosIotResult_(const ContainerAllocator& _alloc)
    : final_x(0)
    , final_y(0)
    , final_theta(0)  {
  (void)_alloc;
    }



   typedef int8_t _final_x_type;
  _final_x_type final_x;

   typedef int8_t _final_y_type;
  _final_y_type final_y;

   typedef int8_t _final_theta_type;
  _final_theta_type final_theta;





  typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> const> ConstPtr;

}; // struct msgRosIotResult_

typedef ::pkg_ros_iot_bridge::msgRosIotResult_<std::allocator<void> > msgRosIotResult;

typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgRosIotResult > msgRosIotResultPtr;
typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgRosIotResult const> msgRosIotResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator1> & lhs, const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_x == rhs.final_x &&
    lhs.final_y == rhs.final_y &&
    lhs.final_theta == rhs.final_theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator1> & lhs, const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_ros_iot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcbe64f721494990ab374cf224b365bf";
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcbe64f721494990ULL;
  static const uint64_t static_value2 = 0xab374cf224b365bfULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_ros_iot_bridge/msgRosIotResult";
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"int8 final_x\n"
"int8 final_y\n"
"int8 final_theta\n"
;
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_x);
      stream.next(m.final_y);
      stream.next(m.final_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgRosIotResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_ros_iot_bridge::msgRosIotResult_<ContainerAllocator>& v)
  {
    s << indent << "final_x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_x);
    s << indent << "final_y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_y);
    s << indent << "final_theta: ";
    Printer<int8_t>::stream(s, indent + "  ", v.final_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROS_IOT_BRIDGE_MESSAGE_MSGROSIOTRESULT_H
